// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: write_files.sql

package db

import (
	"context"
)

const getFileWrite = `-- name: GetFileWrite :one
SELECT session_id, path, written_at FROM write_files
WHERE session_id = ? AND path = ? LIMIT 1
`

type GetFileWriteParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

func (q *Queries) GetFileWrite(ctx context.Context, arg GetFileWriteParams) (WriteFile, error) {
	row := q.queryRow(ctx, q.getFileWriteStmt, getFileWrite, arg.SessionID, arg.Path)
	var i WriteFile
	err := row.Scan(&i.SessionID, &i.Path, &i.WrittenAt)
	return i, err
}

const listSessionWriteFiles = `-- name: ListSessionWriteFiles :many
SELECT session_id, path, written_at FROM write_files
WHERE session_id = ?
ORDER BY written_at DESC
`

func (q *Queries) ListSessionWriteFiles(ctx context.Context, sessionID string) ([]WriteFile, error) {
	rows, err := q.query(ctx, q.listSessionWriteFilesStmt, listSessionWriteFiles, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WriteFile{}
	for rows.Next() {
		var i WriteFile
		if err := rows.Scan(&i.SessionID, &i.Path, &i.WrittenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFileWrite = `-- name: RecordFileWrite :exec
INSERT INTO write_files (
    session_id,
    path,
    written_at
) VALUES (
    ?,
    ?,
    strftime('%s', 'now')
) ON CONFLICT(path, session_id) DO UPDATE SET
    written_at = excluded.written_at
`

type RecordFileWriteParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

func (q *Queries) RecordFileWrite(ctx context.Context, arg RecordFileWriteParams) error {
	_, err := q.exec(ctx, q.recordFileWriteStmt, recordFileWrite, arg.SessionID, arg.Path)
	return err
}
